[package]

name = "gh-emoji"
version = "1.0.0"
authors = ["Kornel <kornel@geekhood.net>", "Jiří Šebele <sindriava@gmail.com>"]

description = "Convert :emoji: to Unicode using GitHub's emoji names"
repository = "https://github.com/kornelski/gh-emoji"
homepage = "https://github.com/kornelski/gh-emoji"
readme = "README.md"
license = "MIT"
include = ["/src/*.rs", "/LICENSE", "/README.md", "/Cargo.toml"]

[dependencies]
phf = "0.7.23"
regex = "1.1.0"
