[package]
name = "gh-emoji-generate"
version = "0.1.1"
authors = ["Kornel <kornel@geekhood.net>", "Jiří Šebele <sindriava@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
phf_codegen = "0.8.0"
serde = "1.0.105"
serde_json = "1.0.48"
serde_derive = "1.0.105"
